name: build-collector
run-name: Build collector by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Dockerfile.collector'
      - '.github/workflows/build-collector.yaml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            arch: amd64
          - runner: ubuntu-24.04-arm64
            platform: linux/arm64
            arch: arm64
    
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get short SHA
        id: get-sha
        run: |
          SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Short SHA: $SHORT_SHA"
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push architecture-specific image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/collector:${{ matrix.arch }}-${{ steps.get-sha.outputs.SHORT_SHA }}
          context: .
          file: Dockerfile.collector
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/collector:cache-${{ matrix.arch }}
          cache-to: type=registry,image-manifest=true,oci-mediatypes=true,ref=ghcr.io/${{ github.repository }}/collector:cache-${{ matrix.arch }},mode=max

  manifest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get short SHA
        id: get-sha
        run: |
          SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Short SHA: $SHORT_SHA"
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create and push multi-arch manifest
        run: |
          SHORT_SHA="${{ steps.get-sha.outputs.SHORT_SHA }}"
          
          # Create the main SHA-based tag that tag-collector-latest expects
          MAIN_TAG="ghcr.io/${{ github.repository }}/collector:main-${SHORT_SHA}"
          
          echo "Creating manifest for $MAIN_TAG"
          docker manifest create $MAIN_TAG \
            ghcr.io/${{ github.repository }}/collector:amd64-${SHORT_SHA} \
            ghcr.io/${{ github.repository }}/collector:arm64-${SHORT_SHA}
          docker manifest push $MAIN_TAG 